algo = input('digite algo: ')
pr = type(algo)
sp = algo.isspace()
n = algo.isnumeric()
alf = algo.isalpha()
aln = algo.isalnum()
M = algo.isupper()
m = algo.islower()
cap = algo.istitle()
print ('O tipo primitivo desse valor é:', type(algo)) #funcionaria sem precisar criar as variavéis
print (f'Só tem espaços? {sp}')
print (f'É um número? {n}')
print (f'É alfabético? {alf}' )
print (f'É alfanumérico? {aln}')
print (f'Possui apenas letras maiúsculas? {M}')
print (f'Possui apenas letras minúsculas? {m}')
print (f'Está capitalizado (letras maiúsculas e minúsculas)? {cap}')
